import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import posthog from "posthog-js";

posthog.init("phc_rYxUqJ5TF6Y7znWFBSx0Z2a5eB2sKDOkWxDhvxuBKVa", {
  api_host: "https://us.i.posthog.com",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
